.eslintrc, README.md, package-lock.json, package.json, repositories.json, src/auth.js, src/run.js
Support to run JWT and OAuth based sdk e2e tests
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
=> Add support for SDK e2e

repositories.json
=> temporary remove tvm related tests because of FW rules

package-lock.json
=> Sync with Master

README.md, repositories.json, src/auth.js
=> Add E2E for events SDK

repositories.json
Fixes #25 
Change analytics tests to use jwt token and re-enabled them.
=> Change analytics tests to use jwt token 

repositories.json
closes #29
updated the env Github Secrets
tested locally with credentials
=> fix: enable Events e2e

repositories.json
=> enable audience manager tests

repositories.json, src/auth.js, src/run.js
Closes #19
populate a `.env` with valid values
change repositories.json aio-lib-ims branch to `e2e-tests`
`node src/run.js`
=> feat: add aio-lib-ims e2e tests

.github/workflows/node.js.yml, README.md, repositories.json
add: aio-lib-web tests
Fixes #18
=> add: aio-lib-web tests

repositories.json
=> Add runtime library tests

.github/workflows/daily.yml, .github/workflows/run-once.yml
=> fix: e2e tests - add daily cron job and manual trigger Github Actions workflows

.github/workflows/daily.yml, .github/workflows/node.js.yml, .github/workflows/run-once.yml, repositories.json
Add aio-lib-customer-profile e2e tests . Fixes #21 
npm run all
=> Add aio-lib-customer-profile e2e tests

.github/workflows/app-smoke-test.yml
Added asset compute integration test into the app-smoke-test.
This pull from https://github.com/adobe/asset-compute-integration-tests and runs: [index.test.js](https://github.com/adobe/asset-compute-integration-tests/blob/main/test/index.test.js)
This will help in detecting breaking changes.
https://github.com/adobe/aio-e2e-tests/issues/49
=> Add test for asset-compute workers

.github/workflows/app-smoke-test.yml
Closes #58 
Depends on:
Updated tests:
This PR is the test.
=> fix: ACNA-1801 - smoke test for new app plugin

.github/dependabot.yml
Adding dependabot to the repo.
[ACNA-1969](https://jira.corp.adobe.com/browse/ACNA-1969)
=> ACNA-1969 | Add dependabot

.github/workflows/app-smoke-test.yml
Fixes #76 
The daily run is the test
=> fix: ACNA-2095 - remove `npm pkg set`, use Github Action (for node-14)

.github/workflows/node.js.yml
Linking the workflow to external file
[ACNA-1828](https://jira.corp.adobe.com/browse/ACNA-1828)
It removes redundancy, centralises the workflow
=> ACNA-1828 | Externalised the workflow

.github/workflows/app-smoke-test.yml, .github/workflows/asset-compute-smoke-test.yml
closes #131 
- the workflows are the test, will run on demand or daily
=> fix: ACNA-2794 - break out asset-compute daily smoke tests into their own workflow

README.md, repositories.json
to be merged after https://github.com/adobe/aio-cli-plugin-app-storage/pull/7
=> feat: add app storage plugin e2e test

repositories.json
=> fix: update repositories.json - branch is main

.github/workflows/app-smoke-test.yml
follow up on #178 
see https://github.com/adobe/aio-e2e-tests/actions/runs/16468739541/job/46552424460
=> use oauth_s2s tokens on smoke tests
